In [1]:
import scipy.stats as stats

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
dataset = sns.load_dataset('tips')

In [3]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [8]:
dataset_table.values

array([[60, 97],
       [33, 54]])

In [10]:
observed_values = dataset_table.values
print("observed_values \n", observed_values)

observed_values 
 [[60 97]
 [33 54]]


In [11]:
vals =  stats.chi2_contingency(dataset_table)


In [12]:
vals

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [14]:
 Expeceted_values = vals[3]

In [15]:
no_of_rows = len(dataset_table.iloc[0:2,0])
no_of_columns = len(dataset_table.iloc[0,0:2])
ddof = (no_of_rows-1)*(no_of_columns-1)
print("Degree of freedom :-" , ddof)
alpha = 0.05

Degree of freedom :- 1


In [19]:

from scipy.stats import chi2
chi_square = sum([(o-e)**2./e for  o,e in zip(observed_values,Expeceted_values)])
chi_square_statistic =chi_square[0]+chi_square[1]

In [20]:
print("chi-square statistic :-" , chi_square_statistic)

chi-square statistic :- 0.001934818536627623


In [25]:
critical_value  = chi2.ppf(q=1-alpha,df=ddof)
print('critical value:-',critical_value)

critical value:- 3.841458820694124


In [27]:
p_value = 1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:-',p_value)
print('significance level :-', alpha)
print('Degree of freedom:' ,ddof)

p-value:- 0.964915107315732
significance level :- 0.05
Degree of freedom: 1


In [28]:
if chi_square_statistic >= critical_value:
    print("Reject H0,There is a relationship between 2 categorical values")
else:
    print("Retain H0,There is no relationship between 2 categorical values")
if p_value<= alpha:
    print("Reject H0,There is a relationship between 2 categorical values")
else:
    print("Retain H0,There is no relationship between 2 categorical values")


Retain H0,There is no relationship between 2 categorical values
Retain H0,There is no relationship between 2 categorical values
